project_name: datalift

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go vet ./...
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

snapshot:
  name_template: "{{ incpatch .Version }}-next"

report_sizes: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
      - s390x
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=datalift

universal_binaries:
  - replace: false

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

archives:
  - name_template: >-
      {{ .ProjectName }}-{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else if and (eq .Os "darwin" ) (eq .Arch "all") }}ubin
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

brews:
  - tap:
      owner: DataliftHQ
      name: homebrew-tap
    folder: Formula
    goarm: "7"
    homepage: https://datalift.io/
    description: Datalift CLI utility
    license: MPL-2.0
    commit_author:
      name: datalift-ci
      email: support@datalift.io
    test: |
      system "#{bin}/datalift --version"
    dependencies:
      - name: go
        type: optional
      - name: git
    install: |-
      bin.install "datalift"
      bash_completion.install "completions/datalift.bash" => "datalift"
      zsh_completion.install "completions/datalift.zsh" => "_datalift"
      fish_completion.install "completions/datalift.fish"
      man1.install "manpages/datalift.1.gz"
    caveats: "â¤ Thanks for installing the Datalift!"

dockers:
  - image_templates:
      - "ghcr.io/datalifthq/datalift:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Datalift","email":"support@datalift.io"}]'
      - "--label=io.artifacthub.package.license=MPL-2.0"
      - "--label=org.opencontainers.image.description=Platform Orchestrator that helps developers build, deploy, and manage their applications more quickly and easily."
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    extra_files:
      - scripts/entrypoint.sh
  - image_templates:
      - "ghcr.io/datalifthq/datalift:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Datalift","email":"support@datalift.io"}]'
      - "--label=io.artifacthub.package.license=MPL-2.0"
      - "--label=org.opencontainers.image.description=Platform Orchestrator that helps developers build, deploy, and manage their applications more quickly and easily."
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - scripts/entrypoint.sh

docker_manifests:
  - name_template: "ghcr.io/datalifthq/datalift:{{ .Tag }}"
    image_templates:
      - "ghcr.io/datalifthq/datalift:{{ .Tag }}-amd64"
      - "ghcr.io/datalifthq/datalift:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/datalifthq/datalift:latest"
    image_templates:
      - "ghcr.io/DataliftHQ/datalift:{{ .Tag }}-amd64"
      - "ghcr.io/DataliftHQ/datalift:{{ .Tag }}-arm64"

nfpms:
  - id: datalift
    file_name_template: >-
      {{ .ProjectName }}-{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    maintainer: Datalift <support@datalift.io>
    description: Command Line Interface for Datalift
    homepage: https://datalift.io
    license: MPL-2.0
    vendor: Datalift
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/datalift.bash
        dst: /usr/share/bash-completion/completions/datalift
        file_info:
          mode: 0644
      - src: ./completions/datalift.fish
        dst: /usr/share/fish/vendor_completions.d/datalift.fish
        file_info:
          mode: 0644
      - src: ./completions/datalift.zsh
        dst: /usr/share/zsh/vendor-completions/_datalift
        file_info:
          mode: 0644
      - src: ./manpages/datalift.1.gz
        dst: /usr/share/man/man1/datalift.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/datalift/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    dependencies:
      - git
    recommends:
      - golang
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

scoops:
  - name: datalift
    bucket:
      owner: DataliftHQ
      name: scoop-bucket
    folder: bucket
    homepage: https://datalift.io
    description: |
      Platform Orchestrator that helps developers build, deploy, and manage 
      their applications more quickly and easily.
    license: MPL-2.0
    commit_author:
      name: datalift-ci
      email: support@datalift.io

sboms:
  - artifacts: archive

snapcrafts:
  - name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    summary: Platform Orchestrator
    description: |
      Platform Orchestrator that helps developers build, deploy, and manage 
      their applications more quickly and easily.
    grade: devel
    confinement: classic
    publish: true

release:
  footer: |
    **Full Changelog**: https://github.com/DataliftHQ/datalift-cli/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Helping out

    This release is only possible thanks to **all** the support of some **awesome people**!
