name: lint

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    strategy:
      matrix:
        go: ['1.20']
        os: [macos-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
