name: misspell

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - 'v*.*.*'
  pull_request:
    types:
      - labeled

jobs:
  misspell:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"